export {
  CANONICAL_PHASES,
  applyInstallIntent,
  describeInstallBootstrap,
  listProfiles,
  parseYaml,
  normalizeInstallIntent,
  normalizeRouterSchemaV3,
  resolveActivationState,
  resolveRouterState,
  setActivationState,
  setActiveProfile,
  stringifyYaml,
  validateRouterSchemaV3,
  validateRouterConfig,
} from './core/router.js';

export {
  createAgentTeamsLiteIntegrationContract,
  compareOpenCodeSessionSnapshots,
  createMultimodelBrowseContract,
  createMultimodelCompareContract,
  createMultimodelOrchestrationManagerContract,
  createOpenCodeSessionSnapshot,
  createOpenCodeSessionSyncContract,
  createOpenCodeSlashCommandManifest,
  discoverConfigPath,
  detectOpenCodeRuntimeContext,
  activateOpenCodeCommand,
  bootstrapOpenCodeCommand,
  deactivateOpenCodeCommand,
  findProjectRoot,
  formatConfigPathForDisplay,
  getConfigPath,
  getOpenCodeCapabilities,
  loadRouterConfig,
  installOpenCodeCommand,
  renderOpenCodeCommand,
  saveRouterConfig,
  projectShareableMultimodelMetadata,
  tryGetConfigPath,
} from './adapters/opencode/index.js';
